server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Hỗ trợ React Router: Nếu không tìm thấy file, tự động trỏ về index.html
        try_files $uri $uri/ /index.html;
    }
}